/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fule_mesurekeyheight_jni_test_JniTest */

#ifndef _Included_com_fule_mesurekeyheight_jni_test_JniTest
#define _Included_com_fule_mesurekeyheight_jni_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fule_mesurekeyheight_jni_test_JniTest
 * Method:    getPackname
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL jnitest
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
